theme: jekyll-theme-minimal
collections_dir: 
  objects:
    output: true
    permalink: /objects/:name
heading_anchors: true
aux_links: 
  "ZollerTMS-JS":
   - "//traismcallister.me/ZollerTMS-JS/"
   - "//traismcallister.me/ZollerTMS-JS/objects"
